services:
  api:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: slowpace-api
    restart: always
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
    networks:
      - slowpace-network

  web:
    build:
      context: ./apps/mobile
      dockerfile: Dockerfile
    container_name: slowpace-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - slowpace-network

networks:
  slowpace-network:
    driver: bridge