FROM postgres:15

RUN apt-get update && \
    apt-get install -y --no-install-recommends wget ca-certificates gnupg && \
    install -d /etc/apt/keyrings && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/keyrings/postgresql.gpg && \
    sh -c 'echo "deb [signed-by=/etc/apt/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt trixie-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && \
    apt-get update && \
    apt-get install -y --no-install-recommends postgresql-15-cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*