import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner"
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br" className="dark">
      <body className="antialiased">
        {children}
        <Toaster
          toastOptions={{
            classNames: {
              toast: "group toast rounded-xl border shadow-2xl transition-all duration-300",
              error: cn(
                "!bg-rose-950/95 !border-rose-900/50 !text-zinc-50",
                "[&_[data-description]]:!text-rose-100/70",
                "[&_[data-icon]]:text-rose-400"
              ),
              success: "!bg-emerald-950/95 !border-emerald-900/50 !text-zinc-50",
              info: "!bg-zinc-900 !border-zinc-800 !text-zinc-50",
            },
          }}
        />
      </body>
    </html>
  )
}
