name: Deploy Slowpace to Home Server

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > apps/backend/.env
                  echo "PORT=3000" >> apps/backend/.env
                  # add other necessary environment variables here, if needed

            - name: Build and Run Containers
              run: |
                  docker compose -f docker-compose.api.yml down --remove-orphans
                  docker compose -f docker-compose.api.yml up --build -d
                  sleep 5

            - name: Run Prisma Migrations
              run: |
                  # Executes migrations inside the container the was build just before
                  docker exec slowpace-api npx prisma migrate deploy
