name: Deploy Slowpace to Home Server

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Build and Run Containers
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
                  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
              run: |
                  docker compose -f docker-compose.api.yml down --remove-orphans
                  docker compose -f docker-compose.api.yml up --build -d
                  sleep 20

            - name: Run Prisma Migrations
              run: |
                  docker exec -w /usr/src/app slowpace-api npx tsx node_modules/prisma/build/index.js migrate deploy
